export const orbLightness = (audioFeature, featureValue) => {
  let lightness;
  let hue;
  let saturation;

  if (audioFeature === "energy") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 39;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 41;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 43;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 45;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 47;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 49;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 51;
      hue = 189;
      saturation = 100;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 39;
      hue = 295;
      saturation = 100;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 41;
      hue = 295;
      saturation = 100;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 43;
      hue = 295;
      saturation = 100;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 45;
      hue = 295;
      saturation = 100;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 47;
      hue = 295;
      saturation = 100;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 49;
      hue = 295;
      saturation = 100;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 51;
      hue = 0;
      saturation = 100;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 39;
      hue = 0;
      saturation = 100;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 41;
      hue = 0;
      saturation = 100;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 43;
      hue = 0;
      saturation = 100;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 45;
      hue = 0;
      saturation = 100;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 47;
      hue = 0;
      saturation = 100;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 49;
      hue = 0;
      saturation = 100;
    }
  } else if (audioFeature === "danceability") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 35;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 36;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 37;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 38;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 39;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 40;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 41;
      hue = 282;
      saturation = 45;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 42;
      hue = 105;
      saturation = 42;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 43;
      hue = 105;
      saturation = 42;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 44;
      hue = 105;
      saturation = 42;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 45;
      hue = 105;
      saturation = 42;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 46;
      hue = 105;
      saturation = 42;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 47;
      hue = 105;
      saturation = 42;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 48;
      hue = 120;
      saturation = 42;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 49;
      hue = 120;
      saturation = 100;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 50;
      hue = 120;
      saturation = 100;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 51;
      hue = 120;
      saturation = 100;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 52;
      hue = 120;
      saturation = 100;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 53;
      hue = 120;
      saturation = 100;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 54;
      hue = 120;
      saturation = 100;
    }
  } else if (audioFeature === "acousticness") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 45;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 46;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 47;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 48;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 49;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 50;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 51;
      hue = 209;
      saturation = 100;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 52;
      hue = 207;
      saturation = 58;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 53;
      hue = 207;
      saturation = 58;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 54;
      hue = 207;
      saturation = 58;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 55;
      hue = 207;
      saturation = 58;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 56;
      hue = 207;
      saturation = 58;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 57;
      hue = 207;
      saturation = 58;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 58;
      hue = 39;
      saturation = 58;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 59;
      hue = 39;
      saturation = 100;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 60;
      hue = 39;
      saturation = 100;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 61;
      hue = 39;
      saturation = 100;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 62;
      hue = 39;
      saturation = 100;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 63;
      hue = 39;
      saturation = 100;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 64;
      hue = 39;
      saturation = 100;
    }
  } else if (audioFeature === "valence") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 50;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 51;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 52;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 53;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 54;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 55;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 56;
      hue = 170;
      saturation = 50;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 57;
      hue = 165;
      saturation = 89;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 58;
      hue = 165;
      saturation = 89;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 59;
      hue = 165;
      saturation = 89;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 60;
      hue = 165;
      saturation = 89;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 61;
      hue = 165;
      saturation = 89;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 62;
      hue = 165;
      saturation = 89;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 63;
      hue = 81;
      saturation = 89;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 64;
      hue = 81;
      saturation = 100;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 65;
      hue = 81;
      saturation = 100;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 66;
      hue = 81;
      saturation = 100;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 67;
      hue = 81;
      saturation = 100;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 68;
      hue = 81;
      saturation = 100;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 69;
      hue = 81;
      saturation = 100;
    }
  } else if (audioFeature === "tempo") {
    if (featureValue >= 0 && featureValue <= 10) {
      lightness = 40;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 10 && featureValue <= 20) {
      lightness = 41;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 20 && featureValue <= 30) {
      lightness = 42;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 30 && featureValue <= 40) {
      lightness = 43;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 40 && featureValue <= 50) {
      lightness = 44;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 50 && featureValue <= 60) {
      lightness = 45;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 60 && featureValue <= 70) {
      lightness = 46;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 70 && featureValue <= 80) {
      lightness = 47;
      hue = 255;
      saturation = 77;
    } else if (featureValue > 80 && featureValue <= 90) {
      lightness = 48;
      hue = 255;
      saturation = 55;
    } else if (featureValue > 90 && featureValue <= 100) {
      lightness = 49;
      hue = 255;
      saturation = 55;
    } else if (featureValue > 100 && featureValue <= 110) {
      lightness = 50;
      hue = 255;
      saturation = 55;
    } else if (featureValue > 110 && featureValue <= 120) {
      lightness = 51;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 120 && featureValue <= 130) {
      lightness = 52;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 130 && featureValue <= 140) {
      lightness = 53;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 140 && featureValue <= 150) {
      lightness = 54;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 150 && featureValue <= 160) {
      lightness = 55;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 160 && featureValue <= 170) {
      lightness = 56;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 170 && featureValue <= 180) {
      lightness = 57;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 180 && featureValue <= 190) {
      lightness = 58;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 190 && featureValue <= 200) {
      lightness = 59;
      hue = 305;
      saturation = 55;
    } else if (featureValue > 200) {
      lightness = 60;
      hue = 305;
      saturation = 55;
    }
  }
  return [lightness, hue, saturation];
};
