export const orbLightness = (audioFeature, featureValue) => {
  let lightness;

  if (audioFeature === "energy") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 30;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 31;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 32;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 33;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 34;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 35;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 36;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 37;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 38;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 39;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 40;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 41;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 42;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 43;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 44;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 45;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 46;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 47;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 48;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 49;
    } else lightness = 50;
  } else if (audioFeature === "danceability") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 35;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 36;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 37;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 38;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 39;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 40;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 41;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 42;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 43;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 44;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 45;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 46;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 47;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 48;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 49;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 50;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 51;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 52;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 53;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 54;
    } else lightness = 55;
  } else if (audioFeature === "acousticness") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 45;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 46;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 47;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 48;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 49;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 50;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 51;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 52;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 53;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 54;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 55;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 56;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 57;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 58;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 59;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 60;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 61;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 62;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 63;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 64;
    } else lightness = 65;
  } else if (audioFeature === "valence") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 35;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 36;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 37;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 38;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 39;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 40;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 41;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 42;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 43;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 44;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 45;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 46;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 47;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 48;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 49;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 50;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 51;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 52;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 53;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 54;
    } else lightness = 55;
  } else if (audioFeature === "tempo") {
    if (featureValue >= 0 && featureValue <= 0.05) {
      lightness = 40;
    } else if (featureValue > 0.05 && featureValue <= 0.1) {
      lightness = 41;
    } else if (featureValue > 0.1 && featureValue <= 0.15) {
      lightness = 42;
    } else if (featureValue > 0.15 && featureValue <= 0.2) {
      lightness = 43;
    } else if (featureValue > 0.2 && featureValue <= 0.25) {
      lightness = 44;
    } else if (featureValue > 0.25 && featureValue <= 0.3) {
      lightness = 45;
    } else if (featureValue > 0.3 && featureValue <= 0.35) {
      lightness = 46;
    } else if (featureValue > 0.35 && featureValue <= 0.4) {
      lightness = 47;
    } else if (featureValue > 0.4 && featureValue <= 0.45) {
      lightness = 48;
    } else if (featureValue > 0.45 && featureValue <= 0.5) {
      lightness = 49;
    } else if (featureValue > 0.5 && featureValue <= 0.55) {
      lightness = 50;
    } else if (featureValue > 0.55 && featureValue <= 0.6) {
      lightness = 51;
    } else if (featureValue > 0.6 && featureValue <= 0.65) {
      lightness = 52;
    } else if (featureValue > 0.65 && featureValue <= 0.7) {
      lightness = 53;
    } else if (featureValue > 0.7 && featureValue <= 0.75) {
      lightness = 54;
    } else if (featureValue > 0.75 && featureValue <= 0.8) {
      lightness = 55;
    } else if (featureValue > 0.8 && featureValue <= 0.85) {
      lightness = 56;
    } else if (featureValue > 0.85 && featureValue <= 0.9) {
      lightness = 57;
    } else if (featureValue > 0.9 && featureValue <= 0.95) {
      lightness = 58;
    } else if (featureValue > 0.95 && featureValue <= 1) {
      lightness = 59;
    } else lightness = 60;
  }
  return lightness;
};
